Update link to the issues tracker
hyperledger/fabric-rfcs pull request #60
Opened 2024-10-31 09:47 UTC by C0rWin

Since we no longer use JIRA, we updated the link to reflect the actual issue tracker.

2024-10-31 09:48 UTC, C0rWin commented
created this one to reflects comments from #59, wasn't able to update the original PR

2024-10-31 09:49 UTC, C0rWin commented
@satota2 can you please take a look now?

2024-10-31 11:23 UTC, satota2 requested changes
@C0rWin
Thank you for the update. It appears that the current link directs to an incorrect location under fabric-rfcs.
It should instead point to the correct address with the `https://` prefix.

Other than that, LGTM!

2024-10-31 11:23 UTC, satota2 commented on README.md
> +issue tracking its implementation in the [Fabric issues](github.com/hyperledger/fabric/issues).
```suggestion
issue tracking its implementation in the [Fabric issues](https://github.com/hyperledger/fabric/issues).
```

2024-10-31 14:31 UTC, C0rWin commented
> @C0rWin Thank you for the update. It appears that the current link directs to an incorrect location under fabric-rfcs. It should instead point to the correct address with the `https://` prefix.
> 
> Other than that, LGTM!

I am not sure why, but I cannot update the current branch as it is marked as protected...

2024-11-01 00:56 UTC, satota2 commented
@C0rWin
I don’t have the permissions to check the Branch Protection Rules in fabric-rfcs, but it seems that protections may be applied to all branches, not just main.
Creating the PR from a forked repository, like `C0rWin:peer2chaincodeComm`, might work better (though it does mean creating another PR).

@denyeart  Could you please check and review the Branch Protection Rules? Protecting just the main branch should be sufficient.

2024-11-02 03:08 UTC, denyeart commented
> > I am not sure why, but I cannot update the current branch as it is marked as protected...
> 
> @C0rWin I don’t have the permissions to check the Branch Protection Rules in fabric-rfcs, but it seems that protections may be applied to all branches, not just main. Creating the PR from a forked repository, like `C0rWin:peer2chaincodeComm`, might work better (though it does mean creating another PR).
> 
> @denyeart Could you please check and review the Branch Protection Rules? Protecting just the main branch should be sufficient.

We don't allow force pushes in any of the repositories, don't want to risk changing the history and don't want to maintain branch protection rules for multiple branches. I always fork and PR from my own fork, I thought that was a pretty standard approach?

2024-11-05 08:07 UTC, satota2 commented
> We don't allow force pushes in any of the repositories, don't want to risk changing the history and don't want to maintain branch protection rules for multiple branches. I always fork and PR from my own fork, I thought that was a pretty standard approach?

@denyeart 
Thank you very much for your feedback. After looking into the branches in the Fabric core repository, I noticed that not all branches are protected there, so I thought there might be room to consider a similar approach if prioritizing flexibility was a goal.

That said, I completely agree with you that “I always fork and PR from my own fork” is indeed the standard approach, and I fully understand the risks involved in modifying the branch protection rules. Based on this, I’ll withdraw my suggestion.

@C0rWin
Could I kindly ask you to create a new PR with the necessary fixes?

2024-11-20 15:16 UTC, closed without merging